model:
  type: NUNetV1
  params:
    channels: [ 64, 128, 256, 384, 512 ]
    n_inputs: 2
    n_classes: 10
    n_input_channels: 10

training:
  type: ModuleV1
  params:
    key_order: [front, left, right, rear]
    label_key: bev

  log_dir: ...
  num_epochs: 10
  batch_size: 64
  gpu: []

data:
  conversion_map: &conversion_map
    road:
      to: 1
      color:
        - 128
        - 64
        - 128
    sidewalk:
      to: 2
      color:
        - 244
        - 35
        - 232
    parking:
      to: 2
      color:
        - 250
        - 170
        - 160
    person:
      to: 3
      color:
        - 255
        - 0
        - 0
    car:
      to: 4
      color:
        - 0
        - 0
        - 142
    trailer:
      to: 4
      color:
        - 0
        - 0
        - 110
    truck:
      to: 5
      color:
        - 0
        - 0
        - 70
    bus:
      to: 6
      color:
        - 0
        - 60
        - 100
    caravan:
      to: 6
      color:
        - 0
        - 0
        - 90
    twowheeler:
      to: 7
      color:
        - 220
        - 20
        - 60
    motorcycle:
      to: 7
      color:
        - 0
        - 0
        - 230
    bicycle:
      to: 7
      color:
        - 119
        - 11
        - 32
    obstacle:
      to: 8
      color:
        - 0
        - 0
        - 0
    dynamic:
      to: 8
      color:
        - 111
        - 74
        - 0
    ground:
      to: 8
      color:
        - 81
        - 0
        - 81
    railtrack:
      to: 8
      color:
        - 230
        - 150
        - 140
    building:
      to: 8
      color:
        - 70
        - 70
        - 70
    wall:
      to: 8
      color:
        - 102
        - 102
        - 156
    fence:
      to: 8
      color:
        - 190
        - 153
        - 153
    guardrail:
      to: 8
      color:
        - 180
        - 165
        - 180
    bridge:
      to: 8
      color:
        - 150
        - 100
        - 100
    tunnel:
      to: 8
      color:
        - 150
        - 120
        - 90
    pole:
      to: 8
      color:
        - 153
        - 153
        - 153
    polegroup:
      to: 8
      color:
        - 153
        - 153
        - 153
    trafficlight:
      to: 8
      color:
        - 250
        - 170
        - 30
    trafficsign:
      to: 8
      color:
        - 220
        - 220
        - 0
    train:
      to: 8
      color:
        - 0
        - 80
        - 100
    sky:
      to: 8
      color:
        - 70
        - 130
        - 180
    vegetation:
      to: 9
      color:
        - 107
        - 142
        - 35
    terrain:
      to: 9
      color:
        - 152
        - 251
        - 152
    occluded:
      to: 10
      color:
        - 150
        - 150
        - 150
  target_size: &target_size [ 400, 400 ]
  views: &views
    - front
    - left
    - right
    - rear
    - bev

  train_dataset:
    type: MultiFolderMasks
    params:
      root: ...
      classes: *conversion_map
      target_size: *target_size
      folders: *views
  val_dataset:
    type: MultiFolderMasks
    params:
      root: ...
      classes: *conversion_map
      target_size: *target_size
      folders: *views
